---
# Copyright 2015, Ian Cordasco
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create the Searchlight system group
  group:
    name: "{{ searchlight_system_group_name }}"
    state: "present"
    system: "yes"
  tags:
    - searchlight-group

- name: Create the Searchlight system user
  user:
    name: "{{ searchlight_system_user_name }}"
    group: "{{ searchlight_system_group_name }}"
    comment: "{{ searchlight_system_comment }}"
    shell: "{{ searchlight_system_shell }}"
    system: "yes"
    createhome: "yes"
    home: "{{ searchlight_system_user_home }}"
  tags:
    - searchlight-user

- name: Create Searchlight directories
  file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "{{ item.owner |default(searchlight_system_user_name) }}"
    group: "{{ item.owner |default(searchlight_system_group_name) }}"
    mode: "{{ item.mode |default('0750') }}"
  with_items:
    - path: "/etc/searchlight"
    - path: "{{ searchlight_system_user_home }}"
  tags:
    - searchlight-directories

- name: Test for Searchlight log directory or link
  shell: |
    if [ -h "{{ searchlight_log_directory }}" ]; then
      chown -h {{ searchlight_system_user_name }}:{{ searchlight_system_group_name }} {{ searchlight_log_directory }}
      chown -R {{ searchlight_system_user_name }}:{{ searchlight_system_group_name }} "$(readlink {{ searchlight_log_directory }})"
    else
      exit 1
    fi
  register: log_dir
  failed_when: false
  changed_when: log_dir.rc != 0
  tags:
    - searchlight-directories
    - searchlight-logs

- name: Create Searchlight log directory
  file:
    path: "{{ searchlight_log_directory }}"
    state: "directory"
    owner: "{{ searchlight_system_user_name }}"
    group: "{{ searchlight_system_group_name }}"
    mode: "0750"
  when: log_dir.rc != 0
  tags:
    - searchlight-directories
    - searchlight-logs

- name: Get the Searchlight source
  git:
    repo: "{{ searchlight_git_url }}"
    version: "{{ searchlight_git_install_branch }}"
    dest: "{{ searchlight_git_dest }}"
    force: yes
  register: searchlight_git_clone
  until: searchlight_git_clone|success
  retries: 5
  delay: 2
  tags:
    - searchlight-git-clone
